[package]
name = "ab"
version = "0.1.0"
authors = ["Mu-An Chiou <me@muanchiou.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
